helmCharts:
  - name: onechart
    releaseName: kolc-discord-bot
    namespace: managed
    version: 0.70.0
    repo: https://chart.onechart.dev
    valuesInline:
      image:
        repository: harbor.androz2091.fr/fiverr-discord-bots/kolc
        tag: 88530c28
      secretName: kolc-discord-bot-secrets
      ports:
      - svcPort: 80
        name: http
        containerPort: 3000
      imagePullSecrets:
      - regcred
      resources:
        limits:
          cpu: "2000m"
          memory: "2000Mi"

namespace: managed

resources:
  - sealed-secrets.yaml

patches: []
